import { useState } from "react";



const InvoiceRightPanel = ({ invoice = {} }) => {

    return (
        <div className="flex flex-col ">

            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto illum natus aut esse inventore quos delectus porro beatae. Vero tempora velit earum? Provident non dolores ad asperiores facere explicabo facilis? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quaerat voluptate tempora nesciunt, suscipit natus ab, autem similique tenetur tempore rem ipsam facilis debitis accusantium ad id ut possimus quod laborum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda non nostrum soluta rerum repudiandae accusantium vel facilis quidem ducimus ipsa, quisquam saepe tempore veritatis nihil ipsum, ratione explicabo corporis dolor.log
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. A dolorem modi sapiente. Blanditiis ducimus optio fugiat itaque quis quidem asperiores tempore veritatis necessitatibus, distinctio temporibus perspiciatis et iure odio tenetur. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vel culpa cupiditate eius blanditiis ab placeat quam tenetur dolor incidunt aspernatur officiis reiciendis nisi perspiciatis quibusdam earum, nihil pariatur sequi beatae? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum, obcaecati maxime recusandae adipisci vero laborum veritatis ipsam dolores nobis tempora quas labore optio earum nostrum? Cumque eaque dolore quas odio?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto illum natus aut esse inventore quos delectus porro beatae. Vero tempora velit earum? Provident non dolores ad asperiores facere explicabo facilis? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quaerat voluptate tempora nesciunt, suscipit natus ab, autem similique tenetur tempore rem ipsam facilis debitis accusantium ad id ut possimus quod laborum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda non nostrum soluta rerum repudiandae accusantium vel facilis quidem ducimus ipsa, quisquam saepe tempore veritatis nihil ipsum, ratione explicabo corporis dolor.log
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. A dolorem modi sapiente. Blanditiis ducimus optio fugiat itaque quis quidem asperiores tempore veritatis necessitatibus, distinctio temporibus perspiciatis et iure odio tenetur. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vel culpa cupiditate eius blanditiis ab placeat quam tenetur dolor incidunt aspernatur officiis reiciendis nisi perspiciatis quibusdam earum, nihil pariatur sequi beatae? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum, obcaecati maxime recusandae adipisci vero laborum veritatis ipsam dolores nobis tempora quas labore optio earum nostrum? Cumque eaque dolore quas odio?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto illum natus aut esse inventore quos delectus porro beatae. Vero tempora velit earum? Provident non dolores ad asperiores facere explicabo facilis? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quaerat voluptate tempora nesciunt, suscipit natus ab, autem similique tenetur tempore rem ipsam facilis debitis accusantium ad id ut possimus quod laborum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda non nostrum soluta rerum repudiandae accusantium vel facilis quidem ducimus ipsa, quisquam saepe tempore veritatis nihil ipsum, ratione explicabo corporis dolor.log
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. A dolorem modi sapiente. Blanditiis ducimus optio fugiat itaque quis quidem asperiores tempore veritatis necessitatibus, distinctio temporibus perspiciatis et iure odio tenetur. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vel culpa cupiditate eius blanditiis ab placeat quam tenetur dolor incidunt aspernatur officiis reiciendis nisi perspiciatis quibusdam earum, nihil pariatur sequi beatae? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum, obcaecati maxime recusandae adipisci vero laborum veritatis ipsam dolores nobis tempora quas labore optio earum nostrum? Cumque eaque dolore quas odio?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto illum natus aut esse inventore quos delectus porro beatae. Vero tempora velit earum? Provident non dolores ad asperiores facere explicabo facilis? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quaerat voluptate tempora nesciunt, suscipit natus ab, autem similique tenetur tempore rem ipsam facilis debitis accusantium ad id ut possimus quod laborum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda non nostrum soluta rerum repudiandae accusantium vel facilis quidem ducimus ipsa, quisquam saepe tempore veritatis nihil ipsum, ratione explicabo corporis dolor.log
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. A dolorem modi sapiente. Blanditiis ducimus optio fugiat itaque quis quidem asperiores tempore veritatis necessitatibus, distinctio temporibus perspiciatis et iure odio tenetur. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vel culpa cupiditate eius blanditiis ab placeat quam tenetur dolor incidunt aspernatur officiis reiciendis nisi perspiciatis quibusdam earum, nihil pariatur sequi beatae? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum, obcaecati maxime recusandae adipisci vero laborum veritatis ipsam dolores nobis tempora quas labore optio earum nostrum? Cumque eaque dolore quas odio?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto illum natus aut esse inventore quos delectus porro beatae. Vero tempora velit earum? Provident non dolores ad asperiores facere explicabo facilis? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quaerat voluptate tempora nesciunt, suscipit natus ab, autem similique tenetur tempore rem ipsam facilis debitis accusantium ad id ut possimus quod laborum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda non nostrum soluta rerum repudiandae accusantium vel facilis quidem ducimus ipsa, quisquam saepe tempore veritatis nihil ipsum, ratione explicabo corporis dolor.log
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. A dolorem modi sapiente. Blanditiis ducimus optio fugiat itaque quis quidem asperiores tempore veritatis necessitatibus, distinctio temporibus perspiciatis et iure odio tenetur. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vel culpa cupiditate eius blanditiis ab placeat quam tenetur dolor incidunt aspernatur officiis reiciendis nisi perspiciatis quibusdam earum, nihil pariatur sequi beatae? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum, obcaecati maxime recusandae adipisci vero laborum veritatis ipsam dolores nobis tempora quas labore optio earum nostrum? Cumque eaque dolore quas odio?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto illum natus aut esse inventore quos delectus porro beatae. Vero tempora velit earum? Provident non dolores ad asperiores facere explicabo facilis? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quaerat voluptate tempora nesciunt, suscipit natus ab, autem similique tenetur tempore rem ipsam facilis debitis accusantium ad id ut possimus quod laborum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda non nostrum soluta rerum repudiandae accusantium vel facilis quidem ducimus ipsa, quisquam saepe tempore veritatis nihil ipsum, ratione explicabo corporis dolor.log
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. A dolorem modi sapiente. Blanditiis ducimus optio fugiat itaque quis quidem asperiores tempore veritatis necessitatibus, distinctio temporibus perspiciatis et iure odio tenetur. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vel culpa cupiditate eius blanditiis ab placeat quam tenetur dolor incidunt aspernatur officiis reiciendis nisi perspiciatis quibusdam earum, nihil pariatur sequi beatae? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum, obcaecati maxime recusandae adipisci vero laborum veritatis ipsam dolores nobis tempora quas labore optio earum nostrum? Cumque eaque dolore quas odio?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto illum natus aut esse inventore quos delectus porro beatae. Vero tempora velit earum? Provident non dolores ad asperiores facere explicabo facilis? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quaerat voluptate tempora nesciunt, suscipit natus ab, autem similique tenetur tempore rem ipsam facilis debitis accusantium ad id ut possimus quod laborum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda non nostrum soluta rerum repudiandae accusantium vel facilis quidem ducimus ipsa, quisquam saepe tempore veritatis nihil ipsum, ratione explicabo corporis dolor.log
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. A dolorem modi sapiente. Blanditiis ducimus optio fugiat itaque quis quidem asperiores tempore veritatis necessitatibus, distinctio temporibus perspiciatis et iure odio tenetur. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vel culpa cupiditate eius blanditiis ab placeat quam tenetur dolor incidunt aspernatur officiis reiciendis nisi perspiciatis quibusdam earum, nihil pariatur sequi beatae? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum, obcaecati maxime recusandae adipisci vero laborum veritatis ipsam dolores nobis tempora quas labore optio earum nostrum? Cumque eaque dolore quas odio?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto illum natus aut esse inventore quos delectus porro beatae. Vero tempora velit earum? Provident non dolores ad asperiores facere explicabo facilis? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quaerat voluptate tempora nesciunt, suscipit natus ab, autem similique tenetur tempore rem ipsam facilis debitis accusantium ad id ut possimus quod laborum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda non nostrum soluta rerum repudiandae accusantium vel facilis quidem ducimus ipsa, quisquam saepe tempore veritatis nihil ipsum, ratione explicabo corporis dolor.log
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. A dolorem modi sapiente. Blanditiis ducimus optio fugiat itaque quis quidem asperiores tempore veritatis necessitatibus, distinctio temporibus perspiciatis et iure odio tenetur. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vel culpa cupiditate eius blanditiis ab placeat quam tenetur dolor incidunt aspernatur officiis reiciendis nisi perspiciatis quibusdam earum, nihil pariatur sequi beatae? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum, obcaecati maxime recusandae adipisci vero laborum veritatis ipsam dolores nobis tempora quas labore optio earum nostrum? Cumque eaque dolore quas odio?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto illum natus aut esse inventore quos delectus porro beatae. Vero tempora velit earum? Provident non dolores ad asperiores facere explicabo facilis? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quaerat voluptate tempora nesciunt, suscipit natus ab, autem similique tenetur tempore rem ipsam facilis debitis accusantium ad id ut possimus quod laborum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda non nostrum soluta rerum repudiandae accusantium vel facilis quidem ducimus ipsa, quisquam saepe tempore veritatis nihil ipsum, ratione explicabo corporis dolor.log
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. A dolorem modi sapiente. Blanditiis ducimus optio fugiat itaque quis quidem asperiores tempore veritatis necessitatibus, distinctio temporibus perspiciatis et iure odio tenetur. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vel culpa cupiditate eius blanditiis ab placeat quam tenetur dolor incidunt aspernatur officiis reiciendis nisi perspiciatis quibusdam earum, nihil pariatur sequi beatae? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum, obcaecati maxime recusandae adipisci vero laborum veritatis ipsam dolores nobis tempora quas labore optio earum nostrum? Cumque eaque dolore quas odio?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto illum natus aut esse inventore quos delectus porro beatae. Vero tempora velit earum? Provident non dolores ad asperiores facere explicabo facilis? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quaerat voluptate tempora nesciunt, suscipit natus ab, autem similique tenetur tempore rem ipsam facilis debitis accusantium ad id ut possimus quod laborum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda non nostrum soluta rerum repudiandae accusantium vel facilis quidem ducimus ipsa, quisquam saepe tempore veritatis nihil ipsum, ratione explicabo corporis dolor.log
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. A dolorem modi sapiente. Blanditiis ducimus optio fugiat itaque quis quidem asperiores tempore veritatis necessitatibus, distinctio temporibus perspiciatis et iure odio tenetur. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vel culpa cupiditate eius blanditiis ab placeat quam tenetur dolor incidunt aspernatur officiis reiciendis nisi perspiciatis quibusdam earum, nihil pariatur sequi beatae? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum, obcaecati maxime recusandae adipisci vero laborum veritatis ipsam dolores nobis tempora quas labore optio earum nostrum? Cumque eaque dolore quas odio?
        </div>
    );
};

export default InvoiceRightPanel;